go_lang_image: &go_lang_image
  docker:
    - image: circleci/golang:1.14
work_directory: &work_directory
  working_directory: ~/vela-template-tester

version: 2.1
jobs:
  test:
    <<: *go_lang_image
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go vet
  build:
    <<: *go_lang_image
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go build -o docker/velatemplatetesterapi app.go
      - save_cache:
          paths:
            - "/go/pkg"
          key: v1-pkg-cache
      - persist_to_workspace:
          root: ~/vela-template-tester
          paths:
            - docker/velatemplatetesterapi
  publish:
    docker:
      - image: docker:19.03.6
    <<: *work_directory
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/vela-template-tester
      - run: |
          TAG=0.1.0
          docker build -t devatherock/vela-template-tester-api:$TAG -t devatherock/vela-template-tester-api:latest docker
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/vela-template-tester-api:$TAG
          docker push devatherock/vela-template-tester-api:latest

workflows:
  version: 2
  build_publish:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
  pr_check:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
