go_lang_image: &go_lang_image
  docker:
    - image: circleci/golang:1.14
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

docker_image: &docker_image
  docker:
    - image: docker:19.03.6
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

template_tester_image: &template_tester_image
  docker:
    - image: devatherock/vela-template-tester:0.2.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    
orbs:
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.0.1
  
work_directory: &work_directory
  working_directory: ~/vela-template-tester

resource_class: &resource_class
  resource_class: small
  
executors:
  docker-executor:
    <<: *go_lang_image
    <<: *resource_class
    <<: *work_directory

version: 2.1
jobs:
  test:
    <<: *go_lang_image
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go vet app.go validator.go util.go
  test_plugin:
    <<: *go_lang_image
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go vet plugin.go validator.go util.go

  build:
    <<: *go_lang_image
    <<: *resource_class
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go build -o docker/velatemplatetesterapi app.go validator.go util.go
      - save_cache:
          paths:
            - "/go/pkg"
          key: v1-pkg-cache
      - persist_to_workspace:
          root: ~/vela-template-tester
          paths:
            - docker/velatemplatetesterapi
  build_plugin:
    <<: *go_lang_image
    <<: *resource_class
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go build -o docker/velatemplatetesterplugin plugin.go validator.go util.go
      - save_cache:
          paths:
            - "/go/pkg"
          key: v1-pkg-cache
      - persist_to_workspace:
          root: ~/vela-template-tester
          paths:
            - docker/velatemplatetesterplugin

  publish:
    <<: *docker_image
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/vela-template-tester
      - run: |
          TAG=0.2.0
          docker build -t devatherock/vela-template-tester-api:$TAG -f docker/Api.Dockerfile docker
          docker tag devatherock/vela-template-tester-api:$TAG devatherock/vela-template-tester-api:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/vela-template-tester-api:$TAG
          docker push devatherock/vela-template-tester-api:latest

  test_plugin_single:
    <<: *template_tester_image
    <<: *resource_class
    <<: *work_directory
    environment:
      PARAMETER_INPUT_FILE: "templates/input_template.yml"
      PARAMETER_VARIABLES: '{"notification_branch":"develop","notification_event":"push"}'
      PARAMETER_EXPECTED_OUTPUT: "templates/output_template.yml"
      PARAMETER_LOG_LEVEL: debug
    steps:
      - checkout
      - attach_workspace:
          at: ~/vela-template-tester
      - run: /bin/velatemplatetesterplugin

  test_plugin_list:
    <<: *template_tester_image
    <<: *resource_class
    <<: *work_directory
    environment:
      PARAMETER_TEMPLATES: '[{"input_file":"templates/input_template.yml","variables":{"notification_branch":"develop","notification_event":"push"},"expected_output":"templates/output_template.yml"}]'
    steps:
      - checkout
      - attach_workspace:
          at: ~/vela-template-tester
      - run: /bin/velatemplatetesterplugin

  deploy:
    executor: heroku/default
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - attach_workspace:
          at: ~/vela-template-tester
      - run:
          name: Build and push the docker image to registry.heroku.com
          command: |
            docker build -t registry.heroku.com/vela-template-tester/web -f docker/Api.Dockerfile docker
            heroku container:login
            docker push registry.heroku.com/vela-template-tester/web
            heroku container:release -a vela-template-tester web

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context:
            - docker-credentials
          filters:
            branches:
              only: master
      - publish:
          context:
            - docker-credentials
          requires:
            - build
      - deploy:
          context:
            - docker-credentials
          requires:
            - publish
  create_plugin:
    jobs:
      - build_plugin:
          context:
            - docker-credentials
          filters:
            branches:
              only: master
      - docker/publish:
          executor: docker-executor
          context:
            - docker-credentials
          requires:
            - build_plugin
          image: devatherock/vela-template-tester  
          attach-at: ~/vela-template-tester
          tag: "0.2.0,latest"
          use-remote-docker: true
          docker-username: DOCKER_USERNAME
          dockerfile: Plugin.Dockerfile
          path: docker
      - test_plugin_single:
          context:
            - docker-credentials
          requires:
            - docker/publish
      - test_plugin_list:
          context:
            - docker-credentials
          requires:
            - docker/publish
  pr_check:
    jobs:
      - test:
          context:
            - docker-credentials
          filters:
            branches:
              ignore: master
      - test_plugin:
          context:
            - docker-credentials
          filters:
            branches:
              ignore: master
