docker_auth: &docker_auth
  auth:
    username: $DOCKER_USERNAME
    password: $DOCKER_PASSWORD

vm_executor_image: &vm_executor_image
  machine:
    image: ubuntu-2204:2023.04.2    

workspace: &workspace
  at: ~/vela-template-tester

work_directory: &work_directory
  working_directory: ~/vela-template-tester

resource_class: &resource_class
  resource_class: small

release_filter: &release_filter
  filters:
    branches:
      only: non-existent-branch
    tags:
      only: /^v[0-9\.]+$/

pr_filter: &pr_filter
  filters:
    branches:
      ignore: master

orbs:
  templates: devatherock/circleci-templates@0.7.0

parameters:
  go_version:
    type: string
    default: "1.20"
  repo_name:
    type: string
    default: "vela-template-tester"  

executors:
  docker-executor:
    docker:
      - image: cimg/go:<< pipeline.parameters.go_version >>
        <<: *docker_auth
    <<: *resource_class
    <<: *work_directory
  template-tester:
    docker:
      - image: devatherock/vela-template-tester:latest
        <<: *docker_auth
    <<: *resource_class
    <<: *work_directory
  machine-executor:
    <<: *vm_executor_image
    resource_class: medium
    <<: *work_directory
  arm-executor:
    <<: *vm_executor_image
    resource_class: arm.medium
    <<: *work_directory

version: 2.1
jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache-{{ checksum "go.mod" }}
            - v1-pkg-cache
      - run: make check

  fast_functional_test:
    parameters:
      image_type:
        type: string
    executor: arm-executor
    steps:
      - checkout
      - run: |
          make docker-build-<< parameters.image_type >> functional-test-<< parameters.image_type >> skip_pull=true

  build:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache-{{ checksum "go.mod" }}
            - v1-pkg-cache
      - run: |
          make coveralls
          make build-all
          make integration-test
      - save_cache:
          paths:
            - "/home/circleci/go/pkg"
          key: v1-pkg-cache-{{ checksum "go.mod" }}

  publish:
    parameters:
      command_args:
        type: string
      docker_image:
        type: string
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          <<: *workspace
      - run: |
          TAG=${CIRCLE_SHA1:0:8}
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker buildx create --name rockbuilder \
            --driver docker-container --use --bootstrap
          docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --push \
              --build-arg GO_VERSION=<< pipeline.parameters.go_version >> \
              -t devatherock/<< parameters.docker_image >>:$TAG \
              -t devatherock/<< parameters.docker_image >>:latest \
              << parameters.command_args >>

  test_plugin_single:
    executor: template-tester
    environment:
      PARAMETER_INPUT_FILE: "test/testdata/input_template.yml"
      PARAMETER_VARIABLES: '{"notification_branch":"develop","notification_event":"push"}'
      PARAMETER_EXPECTED_OUTPUT: "test/testdata/output_template.yml"
      PARAMETER_LOG_LEVEL: debug
    steps:
      - checkout
      - attach_workspace:
          <<: *workspace
      - run: /bin/velatemplatetesterplugin

  test_plugin_list:
    executor: template-tester
    environment:
      PARAMETER_TEMPLATES: '[{"input_file":"test/testdata/input_template.yml","variables":{"notification_branch":"develop","notification_event":"push"},"expected_output":"test/testdata/output_template.yml"}]'
    steps:
      - checkout
      - attach_workspace:
          <<: *workspace
      - run: /bin/velatemplatetesterplugin

  functional_test:
    parameters:
      command_args:
        type: string
      runner:
        type: executor
    executor: << parameters.runner >>
    steps:
      - checkout
      - run: |
          make << parameters.command_args >>

  release:
    executor: docker-executor
    parameters:
      docker_image:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          <<: *workspace
      - run: |
          TAG=${CIRCLE_TAG#v}
          DEV_TAG=${CIRCLE_SHA1:0:8}
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker buildx create --name rockbuilder \
            --driver docker-container --use --bootstrap
          docker buildx imagetools create \
            -t devatherock/<< parameters.docker_image >>:$TAG \
            devatherock/<< parameters.docker_image >>:$DEV_TAG

  deploy:
    executor: docker-executor
    steps:
      - run:
          name: Trigger deployment to render.com
          command: |
            curl $RENDER_DEPLOY_HOOK

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - templates/slack:
          name: notify
          context:
            - docker-credentials
            - slack-webhook
          filters:
            branches:
              only: master    
      - build:
          context:
            - docker-credentials
          requires:
            - notify  
      - publish:
          name: publish_api
          context:
            - docker-credentials
          command_args: '-f build/Api.Dockerfile .'
          docker_image: 'vela-template-tester-api'
          requires:
            - build
      - publish:
          name: publish_plugin
          context:
            - docker-credentials
          command_args: '-f build/Plugin.Dockerfile .'
          docker_image: 'vela-template-tester'
          requires:
            - build
      - templates/dockerhub_readme_update:
          name: dockerhub_readme_api
          context:
            - docker-credentials
            - dockerhub-readme-credentials
          docker_image: 'vela-template-tester-api'
          image_description: 'API to test and validate vela-ci templates'
          work_dir: '~/<< pipeline.parameters.repo_name >>'
          requires:
            - publish_api
      - templates/dockerhub_readme_update:
          name: dockerhub_readme_plugin
          context:
            - docker-credentials
            - dockerhub-readme-credentials
          docker_image: '<< pipeline.parameters.repo_name >>'
          image_description: 'Plugin to test and validate vela-ci templates'
          work_dir: '~/<< pipeline.parameters.repo_name >>'
          requires:
            - publish_plugin
      - test_plugin_single:
          context:
            - docker-credentials
          requires:
            - dockerhub_readme_plugin
      - test_plugin_list:
          context:
            - docker-credentials
          requires:
            - dockerhub_readme_plugin
      - functional_test:
          name: functional_test_api
          context:
            - docker-credentials
          command_args: 'functional-test-api'
          runner: machine-executor
          requires:
            - dockerhub_readme_api
      - functional_test:
          name: functional_test_plugin
          context:
            - docker-credentials
          command_args: 'functional-test-plugin'
          runner: machine-executor
          requires:
            - dockerhub_readme_plugin
      - functional_test:
          name: functional_test_api_arm
          context:
            - docker-credentials
          command_args: 'functional-test-api'
          runner: arm-executor
          requires:
            - dockerhub_readme_api
      - functional_test:
          name: functional_test_plugin_arm
          context:
            - docker-credentials
          command_args: 'functional-test-plugin'
          runner: arm-executor
          requires:
            - test_plugin_single
            - test_plugin_list

  release_api:
    jobs:
      - templates/slack:
          name: notify
          context:
            - docker-credentials
            - slack-webhook
          <<: *release_filter
      - release:
          name: release_api
          context:
            - docker-credentials
          docker_image: vela-template-tester-api
          <<: *release_filter
          requires:
            - notify
      - deploy:
          context:
            - docker-credentials
          <<: *release_filter
          requires:
            - release_api

  release_plugin:
    jobs:
      - templates/slack:
          name: notify
          context:
            - docker-credentials
            - slack-webhook
          <<: *release_filter    
      - release:
          name: release_plugin
          context:
            - docker-credentials
          docker_image: vela-template-tester
          <<: *release_filter
          requires:
            - notify

  pr_check:
    jobs:
      - templates/changelog_updater:
          name: changelog_updater
          context:
            - docker-credentials
            - changelog-updater-credentials
          <<: *pr_filter
      - test:
          context:
            - docker-credentials
          requires:
            - changelog_updater
      - fast_functional_test:
          name: fast_functional_test_api
          context:
            - docker-credentials
          image_type: 'api'
          requires:
            - test
      - fast_functional_test:
          name: fast_functional_test_plugin
          context:
            - docker-credentials
          image_type: 'plugin'
          requires:
            - test
